# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlonKlsXxI4Dc0OPkSZ1mJluV7196tws
"""

import random

hadani = True
while hadani:
    print("Ahoj, zahrajem si takovou hru. Hádej čtyřmístné číslo. Číslo nesmí obsahovat duplikáty a nesmí začínat nulou.")

    while True:
        cislo_jedna = random.randrange(1, 10)
        cislo_dva = random.randrange(0, 10)
        cislo_tri = random.randrange(0, 10)
        cislo_ctyri = random.randrange(0, 10)

        if (cislo_jedna != cislo_dva and cislo_jedna != cislo_tri and cislo_jedna != cislo_ctyri and
                cislo_dva != cislo_tri and cislo_dva != cislo_ctyri and cislo_tri != cislo_ctyri):
            break

    nahod_cislo = str(cislo_jedna) + str(cislo_dva) + str(cislo_tri) + str(cislo_ctyri)

    while True:
        try:
            uzivatel_cislo = input("Zadej své čtyřmístné číslo: ")

            if len(uzivatel_cislo) != 4 or not uzivatel_cislo.isdigit():
                print("Zadej čtyřmístné číslo obsahující pouze číslice!")
                continue
            if len(set(uzivatel_cislo)) != 4:
                print("Číslo nesmí obsahovat duplikáty!")
                continue
            if uzivatel_cislo[0] == '0':
                print("Číslo nesmí začínat nulou!")
                continue
        except ValueError:
            print("Nastala chyba při zadávání čísla. Zkus to znovu!")
            continue

        bull = 0
        cow = 0

        if uzivatel_cislo[0] == str(cislo_jedna):
            bull += 1
        elif uzivatel_cislo[0] in nahod_cislo:
            cow += 1

        if uzivatel_cislo[1] == str(cislo_dva):
            bull += 1
        elif uzivatel_cislo[1] in nahod_cislo:
            cow += 1

        if uzivatel_cislo[2] == str(cislo_tri):
            bull += 1
        elif uzivatel_cislo[2] in nahod_cislo:
            cow += 1

        if uzivatel_cislo[3] == str(cislo_ctyri):
            bull += 1
        elif uzivatel_cislo[3] in nahod_cislo:
            cow += 1

        bull_text = "bull" if bull == 1 else "bulls"
        cow_text = "cow" if cow == 1 else "cows"

        print(str(bull) + " " + bull_text + ", " + str(cow) + " " + cow_text)

        if uzivatel_cislo == nahod_cislo:
            print("Gratuluji! Uhodl jsi číslo " + nahod_cislo + ".")
            odpoved = input("Chceš hrát dál? (ANO/NE): ").strip().upper()
            if odpoved == "ANO":
                break
            else:
                print("Program se zavírá.")
                hadani = False
                break

